# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [15]:
# Import torch
import torch


# Create random tensor
tensor = torch.randn(7, 7)
tensor

tensor([[ 0.4653, -0.3963, -0.1504, -0.3525, -2.1235, -0.7741,  0.1584],
        [ 1.2519, -0.0366, -0.6005,  0.4946,  1.0515,  1.6861, -1.8872],
        [ 0.2780, -0.5448, -0.2815, -0.1859,  0.3180,  1.0716,  0.6935],
        [-0.3435, -1.7332, -0.8669,  1.1169,  1.1471,  0.2808, -0.7255],
        [-0.6354,  0.5837, -0.8458,  0.2554, -0.5851, -0.7346,  1.2272],
        [-1.6442, -0.1696, -1.5282,  1.1278,  0.9990,  0.1671,  0.6792],
        [ 0.1366,  1.9107,  0.3589,  0.2545,  0.9555, -0.7470,  1.0279]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [17]:
# Create another random tensor
A = torch.rand(7).reshape(1,7)
#B = torch.arange(1,8).reshape(1,7)
torch.matmul(tensor, A.T)
# Perform matrix multiplication 


tensor([[-1.0711],
        [ 2.2131],
        [ 0.8230],
        [-0.8870],
        [-1.7542],
        [-2.1521],
        [ 0.7147]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
X = torch.rand(7,7, generator=torch.manual_seed(RANDOM_SEED))
Y = torch.rand(1,7, generator=torch.manual_seed(RANDOM_SEED))

# Matrix multiply tensors
Z = torch.mm(X, Y.T)

Z, Z.shape

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [19]:

# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [26]:
# Set random seed on the GPU
torch.mps.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [32]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "mps" if torch.backends.mps.is_available() else "cpu"
# Create two random tensors on GPU
A = torch.rand(size=(2, 3)).to(device)
B = torch.rand(size=(2, 3)).to(device)

device, A, B

('mps',
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [34]:
# Perform matmul on tensor_A and tensor_B
Z = A @ B.T
Z

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='mps:0')

### 8. Find the maximum and minimum values of the output of 7.

In [35]:
# Find max
Z.max()
# Find min
Z.min()

tensor(0.3647, device='mps:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [37]:
# Find arg max

Z.argmax()
# Find arg min
Z.argmin()

tensor(0, device='mps:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [38]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(size=(1,1,1,10))

# Remove single dimensions
tensor1 = tensor.squeeze()

# Print out tensors and their shapes
print("Original tensor shape:", tensor.shape)
print("Squeezed tensor shape:", tensor1.shape)

Original tensor shape: torch.Size([1, 1, 1, 10])
Squeezed tensor shape: torch.Size([10])


In [39]:
print("Original tensor:", tensor)
print("Squeezed tensor:", tensor1)

Original tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Squeezed tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
