In [1]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
print(torch.__version__)

2.11.0


In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7, 7])

In [7]:
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#tensor 
TENSOR = torch.tensor([[[1, 2], 
                        [3, 4]],

                       [[5, 6],
                        [7, 8]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([2, 2, 2])

In [16]:
#random tensors
T = torch.rand(3, 4) #3 rows, 4 columns
T

tensor([[0.4575, 0.6868, 0.0382, 0.1158],
        [0.9292, 0.6622, 0.3153, 0.4970],
        [0.3211, 0.2609, 0.1580, 0.1381]])

In [17]:
T = torch.rand(3, 4, 5) #3 rows, 4 columns, 5 depth

In [18]:
T

tensor([[[0.4597, 0.8056, 0.7159, 0.7641, 0.9432],
         [0.0515, 0.9407, 0.5265, 0.3917, 0.7497],
         [0.4382, 0.8791, 0.2937, 0.8612, 0.7403],
         [0.1725, 0.3358, 0.4497, 0.9034, 0.2509]],

        [[0.2326, 0.5570, 0.8597, 0.5211, 0.3160],
         [0.5069, 0.8408, 0.1054, 0.5688, 0.5461],
         [0.4647, 0.5696, 0.0432, 0.7866, 0.7652],
         [0.0157, 0.3560, 0.7652, 0.8229, 0.7618]],

        [[0.5007, 0.8907, 0.8059, 0.5042, 0.1964],
         [0.3880, 0.3908, 0.8216, 0.2988, 0.0917],
         [0.2909, 0.8325, 0.6835, 0.0169, 0.8571],
         [0.1980, 0.7211, 0.4838, 0.9667, 0.4465]]])

In [19]:
random_image = torch.rand(size=(3, 224, 224)) #color channel, height, width
random_image.ndim, random_image.shape, random_image[0][0][0]

(3, torch.Size([3, 224, 224]), tensor(0.2323))

In [20]:
Ones = torch.ones(3, 4)
Ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
Zeros = torch.zeros(3, 4)

In [22]:
Zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
0*T

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [24]:
0*T+1

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [25]:
Ones.dtype

torch.float32

In [26]:
torch.arange(0,10).ndim

1

In [27]:
torch.arange(0,1000, step = 85)

tensor([  0,  85, 170, 255, 340, 425, 510, 595, 680, 765, 850, 935])

In [28]:
#tensors like
ten_zeros = torch.zeros_like(input=T)
ten_zeros

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [29]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=torch.float16,
                                device=None,
                                 requires_grad=False
                               )
float_32_tensor.dtype

torch.float16

In [30]:
tensor = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
tensor + 10

tensor([11., 12., 13., 14., 15.])

In [31]:
tensor*10

tensor([10., 20., 30., 40., 50.])

In [32]:
tensor - 10

tensor([-9., -8., -7., -6., -5.])

In [33]:
tensor.mul(10)

tensor([10., 20., 30., 40., 50.])

In [34]:
tensor.add(3)

tensor([4., 5., 6., 7., 8.])

In [35]:
tensor = torch.arange(0, 4)
tensor

tensor([0, 1, 2, 3])

In [38]:
tensor*tensor #element wise multiplication

tensor([0, 1, 4, 9])

In [37]:
torch.matmul(tensor, tensor)

tensor(14)

In [39]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
value

CPU times: user 618 μs, sys: 2.72 ms, total: 3.34 ms
Wall time: 4.87 ms


tensor(14)

In [40]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 121 μs, sys: 157 μs, total: 278 μs
Wall time: 159 μs


tensor(14)

In [41]:
x = torch.arange(0, 101, 10)
x.dtype

torch.int64

In [47]:
torch.mean(x.to(torch.float32))

tensor(50.)

In [48]:
torch.min(x)

tensor(0)

In [49]:
x.min()

tensor(0)

In [51]:
torch.sum(x)

tensor(550)

In [52]:
x.sum()

tensor(550)

In [53]:
x.argmin()

tensor(0)

In [54]:
x.argmax()

tensor(10)

In [55]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [58]:
x_reshaped = x.reshape(1,-1)

In [59]:
x_reshaped.shape

torch.Size([1, 9])

In [61]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [62]:
x_reshaped.view(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [64]:
z = torch.arange(1,5)
x = torch.arange(1,5)

y = torch.stack((x,z), dim=1)
y

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [70]:
x = torch.zeros(2,1,2,3,4,1,1,5)
x.squeeze().unsqueeze(0).shape

torch.Size([1, 2, 2, 3, 4, 5])

In [72]:
x.shape

torch.Size([2, 1, 2, 3, 4, 1, 1, 5])

In [78]:
x.permute(1,2,3,4,5,6,7,0).shape

torch.Size([1, 2, 3, 4, 1, 1, 5, 2])

In [79]:
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [80]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [81]:
x[0][0]

tensor([1, 2, 3])

In [82]:
x[0][0][0]

tensor(1)

In [83]:
x[0,0,0]

tensor(1)

In [84]:
x[0,0]

tensor([1, 2, 3])

In [85]:
x[0,-1,-1]

tensor(9)

In [86]:
x[:,:,2]

tensor([[3, 6, 9]])

In [87]:
# numpy array to tensor

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [88]:
array.dtype

dtype('float64')

In [89]:
array[0] = 55
array, tensor

(array([55.,  2.,  3.,  4.,  5.,  6.,  7.]),
 tensor([55.,  2.,  3.,  4.,  5.,  6.,  7.], dtype=torch.float64))

In [91]:
array = array + 1
array, tensor

(array([57.,  4.,  5.,  6.,  7.,  8.,  9.]),
 tensor([55.,  2.,  3.,  4.,  5.,  6.,  7.], dtype=torch.float64))

In [92]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [93]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [95]:
torch.rand(3,3)

tensor([[0.4883, 0.3750, 0.1418],
        [0.7710, 0.0417, 0.0783],
        [0.2355, 0.4497, 0.7649]])

In [96]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3,4)

In [97]:
random_tensor_A == random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [100]:
RANDOM_SEED = 42
random_tensor_C = torch.rand(3, 4, generator=torch.manual_seed(RANDOM_SEED))
random_tensor_D = torch.rand(3, 4, generator=torch.manual_seed(RANDOM_SEED))

In [101]:
random_tensor_C == random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [102]:
device = torch.device(
    "mps" if torch.backends.mps.is_available() else "cpu"
)

print(device)

mps


In [ ]:
x = torch.randn(1000, 1000, device=device)
y = torch.randn(1000, 1000, device=device)

z = x @ y
print(z.device)  # mps:0

mps:0


In [109]:
%%time
x = torch.tensor(torch.randn(10000, 10000, device=device))
y = torch.tensor(torch.randn(10000, 10000, device=device))

z = x @ y
print(z.device)  # mps:0

<timed exec>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
<timed exec>:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).


mps:0
CPU times: user 10.3 ms, sys: 101 ms, total: 111 ms
Wall time: 325 ms


In [110]:
%%time
x = torch.randn(10000, 10000, device='cpu')
y = torch.randn(10000, 10000, device='cpu')

z = x @ y
print(z.device)  # mps:0

cpu
CPU times: user 3.75 s, sys: 284 ms, total: 4.03 s
Wall time: 4.27 s


In [106]:
x.shape

torch.Size([1000, 1000])

In [107]:
x.dtype

torch.float32

In [111]:
#create a random tensor and move it to the GPU if available
tensor = torch.tensor([1,2,3], device='cpu')

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [112]:
# move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='mps:0'), device(type='mps', index=0))

In [113]:
# move back to cpu because numpy is not compatible with GPU tensors
tensor_on_cpu = tensor_on_gpu.to('cpu')
tensor_on_cpu, tensor_on_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [116]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()

In [117]:
tensor_back_on_cpu

array([1, 2, 3])