In [1]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
print(torch.__version__)

2.11.0


In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7, 7])

In [7]:
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [14]:
#matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX.ndim

2

In [15]:
MATRIX[0]

tensor([7, 8])

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
#tensor 
TENSOR = torch.tensor([[[1, 2], 
                        [3, 4]],

                       [[5, 6],
                        [7, 8]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([2, 2, 2])

In [20]:
#random tensors
T = torch.rand(3, 4) #3 rows, 4 columns
T

tensor([[0.4273, 0.5275, 0.6064, 0.4093],
        [0.5978, 0.4763, 0.0020, 0.6380],
        [0.0016, 0.4336, 0.2774, 0.8600]])

In [21]:
T = torch.rand(3, 4, 5) #3 rows, 4 columns, 5 depth

In [22]:
T

tensor([[[0.6139, 0.0215, 0.1887, 0.5866, 0.0328],
         [0.6922, 0.5604, 0.3387, 0.2109, 0.4924],
         [0.0281, 0.1054, 0.4013, 0.3085, 0.1081],
         [0.1910, 0.8330, 0.6213, 0.4373, 0.3035]],

        [[0.7911, 0.3378, 0.9742, 0.2174, 0.4996],
         [0.4133, 0.8813, 0.6590, 0.7882, 0.2779],
         [0.2718, 0.6168, 0.9533, 0.8502, 0.7625],
         [0.1040, 0.2346, 0.9094, 0.3295, 0.6258]],

        [[0.7705, 0.2502, 0.8923, 0.8787, 0.2939],
         [0.4413, 0.5540, 0.0667, 0.7429, 0.7139],
         [0.6326, 0.7021, 0.1998, 0.5146, 0.1912],
         [0.6220, 0.0589, 0.6544, 0.8699, 0.0440]]])

In [25]:
random_image = torch.rand(size=(3, 224, 224)) #color channel, height, width
random_image.ndim, random_image.shape, random_image[0][0][0]

(3, torch.Size([3, 224, 224]), tensor(0.6602))

In [26]:
Ones = torch.ones(3, 4)
Ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
Zeros = torch.zeros(3, 4)

In [28]:
Zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
0*T

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [30]:
0*T+1

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [32]:
Ones.dtype

torch.float32

In [35]:
torch.arange(0,10).ndim

1

In [36]:
torch.arange(0,1000, step = 85)

tensor([  0,  85, 170, 255, 340, 425, 510, 595, 680, 765, 850, 935])

In [37]:
#tensors like
ten_zeros = torch.zeros_like(input=T)
ten_zeros

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [41]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=torch.float16,
                                device=None,
                                 requires_grad=False
                               )
float_32_tensor.dtype

torch.float16